[package]
name = "cannycam"
version = "0.1.0"
authors = ["Jason Stelzer <mental@neverlight.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
opencv = "0.93.5"
num-traits = "0.2"
num-derive = "0.4"


