[env]
DYLD_FALLBACK_LIBRARY_PATH =  { value = "/usr/local/lib:/opt/homebrew/lib:/Library/Developer/CommandLineTools/usr/lib/", force = true }

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[env.linux]
CFLAGS = "-I/opt/QtOpenCV/include"
LDFLAGS = "-L/opt/QtOpenCV/lib -lopencv_core -lopencv_imgproc -lopencv_highgui"
LD_LIBRARY_PATH = "/opt/QtOpenCV/lib"
PKG_CONFIG_PATH = "/opt/QtOpenCV/lib/pkgconfig:/opt/QtOpenCV/share/pkgconfig"
# OpenCV crate environment variables
OPENCV_INCLUDE_PATH = "/opt/QtOpenCV/include"
OPENCV_LIB_PATH = "/opt/QtOpenCV/lib"
OPENCV_LINK_LIBS = "opencv_core:opencv_imgproc:opencv_highgui"

[env.macos]
CFLAGS = "-I/opt/QtOpenCV/include"
LDFLAGS = "-L/opt/QtOpenCV/lib -lopencv_core -lopencv_imgproc -lopencv_highgui"
DYLD_LIBRARY_PATH = "/opt/QtOpenCV/lib"
PKG_CONFIG_PATH = "/opt/QtOpenCV/lib/pkgconfig:/opt/QtOpenCV/share/pkgconfig"
# OpenCV crate environment variables
OpenCV_DIR="/opt/QtOpenCV/lib/cmake/opencv4"


[tasks.build]
dependencies = ["format", "dev", "release"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["dev", "release"]

[tasks.dev]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.release]
command = "cargo"
args = ["build", "-r"]
dependencies = ["format"]

