[env]
DYLD_FALLBACK_LIBRARY_PATH =  { value = "/usr/local/lib:/opt/homebrew/lib:/Library/Developer/CommandLineTools/usr/lib/", force = true }

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.build]
dependencies = ["format", "dev", "release"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["dev", "release"]

[tasks.dev]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.release]
command = "cargo"
args = ["build", "-r"]
dependencies = ["format"]

